services:
  nextjs:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql

  express:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bank
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
