name: BankSajt

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test with React Testing Library v2
    runs-on: ubuntu-latest

    steps:
      - name: Check out Repo
        uses: actions/checkout@v3 # Uppdaterat till v3 för stabilitet

      - name: Set up Node
        uses: actions/setup-node@v3 # Uppdaterat till v3 för stabilitet
        with:
          node-version: "20"

      - name: Install Dependencies
        working-directory: ./
        run: npm ci # Använd npm ci för snabbare och mer konsekvent installation

      - name: Run Tests
        working-directory: ./
        run: npm run test:ci
        env:
          CI: true

  deployment:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out Repo
        uses: actions/checkout@v3 # Uppdaterat till v3 för stabilitet

      - name: Install Docker and Docker Compose on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            # Install Docker
            sudo apt-get update
            sudo apt-get install -y docker.io
            # Install Docker Compose
            sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            sudo systemctl enable docker
            sudo systemctl start docker
            docker --version
            docker-compose --version

      - name: Copy files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "."
          target: "/home/ubuntu/banksajt" # <-- Uppdaterad sökväg

      - name: Run Docker on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            echo "Debugging EC2 setup"
            cd /home/ubuntu/banksajt  # <-- Uppdaterad sökväg
            sudo docker-compose down
            sudo docker-compose up --build -d
