version: "3"
 services:
  nextjs:
    build: ./nextjs
    ports:
      - "3000:3000"

  express:
    build: ./express
    ports:
      - "3001:3001"

  mysql:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
