version: "3.8"
services:
  express:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - .:/app
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: banksajt
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
